config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :books, only: [:new, :create, :index, :update, :destroy]
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, presence: true


  def self.find_for_title(title)
    Book.where(title: title)
  end

  def title_and_author_stringer
    "#{self.title} was written by #{self.author}"
  end

  def self.stringify_all_book_titles
    # Book.all.map do |book|
    #   book.title
    # end.join(', ')

    # Book.all.map { |book| book.title }.join(", ")

    Book.all.map(&:title).join(", ")

    # result = ""
    #
    # Book.all.each do |book|
    #   result << book.title + ", "
    # end
    # result = result[0...-2]
    # result
  end

  def destroy_author
    self.author = nil
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.find_for_title("Harry Potter")
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.new(book_params)
    if book.save
      redirect_to books_path, notice: "Book created"
    else
      @book = book
      flash[:notice] = "Something went wrong"
      render :new
    end
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to root_path, notice: "Book updated"
    else
      @book = book
      flash[:notice] = "Unable to update book"
      render :edit
    end
  end

  def destroy
    Book.destroy(params[:id])
    redirect_to root_path, notice: "Book destroyed"
  end

  private

  def book_params
    params.require(:book).permit(:title, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<%= link_to "New Book", new_book_path %>

<% @books.each do |book| %>

  <%= book.title %>
  <%= book.author %>

<% end %>

app/views/books/new.html.erb
<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.submit "Create Book" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticeControllerSpecs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>